version: '3.8'

services:
  app:
    build: .
    container_name: recipes-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/recipes_book_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:16-alpine
    container_name: recipes-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=recipes_book_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: